---
- hosts: all
  sudo: true
  tasks:
    - name: update apt cache
      apt: update_cache=yes

    - name: upgrade packages
      apt: upgrade=dist

    - name: install packages
      apt: name={{ item }} state=present update_cache=yes
      with_items:
       - nginx
       - git
       - libpq-dev 
       - python-dev
       - postgresql 
       - postgresql-contrib
       - python-virtualenv